export const eng = {
  goals: [
    "No poverty (SDG 1)",
    "Zero hunger (SDG 2)",
    "Good health and well-being (SDG 3)",
    "Quality education (SDG 4)",
    "Gender equality (SDG 5)",
    "Clean water and sanitation (SDG 6)",
    "Affordable and clean energy (SDG 7)",
    "Decent work and economic growth (SDG 8)",
    "Industry, innovation and infrastructure (SDG 9)",
    "Reduced inequalities (SDG 10)",
    "Sustainable cities and communities (SDG 11)",
    "Responsible consumption and production (SDG 12)",
    "Climate action (SDG 13)",
    "Life below water (SDG 14)",
    "Life on land (SDG 15)",
    "Peace, justice, and strong institutions (SDG 16)",
    "Partnerships for the goals (SDG 17)",
  ],
  title: "What are the 17 symbols?",
  subTitle: "Introducing the Sustainable Development Goals",
  body: "IN THE YEAR 2015, LEADERS FROM 193 COUNTRIES OF THE WORLD CAME TOGETHER TO FACE THE FUTURE.\n\nAnd what they saw was daunting. Famines. Drought. Wars. Plagues. Poverty. Not just in some faraway place, but in their own cities and towns and villages. They knew things didn’t have to be this way. They knew we had enough food to feed the world, but that it wasn’t getting shared. They knew there were medicines for HIV and other diseases, but they cost a lot. They knew that earthquakes and floods were inevitable, but that the high death tolls were not.\n\nThey also knew that billions of people worldwide shared their hope for a better future.\n\nSo leaders from these countries created a plan called the Sustainable Development Goals (SDGs). This set of 17 goals imagines a future just 15 years off that would be rid of poverty and hunger, and safe from the worst effects of climate change. It’s an ambitious plan. But there’s ample evidence that we can succeed. In the past 15 years, the international community cut extreme poverty in half.\n\nNow we can finish the job.\n\nThe United Nations Development Programme (UNDP) is one of the leading organizations working to fulfill the SDGs by the year 2030. Present in nearly 170 countries and territories, we help nations make the Goals a reality. We also champion the Goals so that people everywhere know how to do their part.\n\nUNDP is proud to continue as a leader in this global movement.\n\nLearn about the Sustainable Development Goals. What’s your Goal?\n\n",
};
